<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndicatorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 1,'name' => 'Indikator Kemampuan Daya Saing Lokal dari Kabupaten/Kota tentang: ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 1,'name' => 'Indiator Kemudahan dalam Berusaha di Kabupaten/Kota terkait dengan:','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 2,'name' => 'Indikator Kecenderungan Korupsi dalam 1 tahun terakhir terkait dengan:','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 2,'name' => 'Kecenderungan Korupsi Saat ini','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 2,'name' => 'Penilaian Anda terhadap kemungkinan Korupsi dalam tahun-tahun mendatang terkait dengan:','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 3,'name' => 'Indikator Mekanisme Akuntabilitas Keuangan Negara dalam 1 tahun terakhir','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 3,'name' => 'Indikator Mekanisme Akuntabilitas Keuangan Negara Saat ini','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 3,'name' => 'Indikator Kemungkinan Mekanisme Akuntabilitas Keuangan dalam tahun-tahun mendatang','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1', 'dimension_id' => 4,'name' => 'Indikator Motivasi Korupsi dalam 1 tahun yang lalu','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 4,'name' => 'Indikator Motivasi Korupsi Saat ini ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 4,'name' => 'Indikator Kemungkinan berkembangnya Motivasi Korupsi dalam tahun-tahun berikutnya ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 5,'name' => 'Indikator Dampak Korupsi dalam 1 tahun sebelumnya ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 5,'name' => 'Indikator Dampak Korupsi Saat ini ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 5,'name' => 'Indikator Kemungkinan Dampak Korupsi dalam tahun-tahun berikutnya ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_4','dimension_id' => 5,'name' => 'Indikator Pemberantasan dan Pencegahan Korupsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 6,'name' => 'Indikator Suap untuk Memenangkan Bisnis ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 6,'name' => 'Indikator Penghambat Menghentikan Suap ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 6,'name' => 'Indikator Upaya dalam Melawan Korupsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_4','dimension_id' => 6,'name' => 'Indikator Adanya Upaya konkret di dalam Internal bisnis dalam memberantas Berbagai Bentuk Korupsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_5','dimension_id' => 6,'name' => 'Indikator Adanya Aksi Efektif Melawan Korupsi di Internal Bisnis ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 7,'name' => 'Indikator Adanya Potensi Suap untuk  MENGAMANKAN PROSES BISNIS  di perusahaan ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 7,'name' => 'Indikator Adanya Potensi Suap untuk  MEMPERCEPAT PROSES ADIMINISTRASI perusahaan ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 7,'name' => 'Indikator Adanya Potensi Suap berbentuk SUMBANGAN POLITIK KEPADA POLITISI yang dilakukan oleh perusahaan ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 8,'name' => 'Indikator Instansi di Tingkat Kabupaten/Kota MEMILIKI STANDARD yang Mengatur tentang PROSEDUR KERJA ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 8,'name' => 'Indikator Instansi di Tingkat Kabupaten/Kota MEMILIKI STANDARD yang Mengatur tentang PROSEDUR WAKTU ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 8,'name' => 'Indikator Instansi di Tingkat Kabupaten/Kota MEMILIKI STANDARD yang Mengatur tentang PROSEDUR BIAYA ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 9,'name' => 'Indikator Instansi di Tingkat Kabupaten/Kota dalam MENGIMPLEMENTASIKAN STANDARD PROSEDUR KERJA ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 9,'name' => 'Indikator Instansi di Tingkat Kabupaten/Kota dalam MENGIMPLEMENTASIKAN STANDARD PROSEDUR WAKTU ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 9,'name' => 'Indikator Instansi di Tingkat Kabupaten/Kota dalam MENGIMPLEMENTASIKAN STANDARD yang mengatur PROSEDUR BIAYA ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 10,'name' => 'Indikator HARAPAN Anda dalam MENCEGAH DAN MEMBERANTAS KORUPSI ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 10,'name' => 'Indikator Penilaian Anda di Kabupaten/Kota ini Terkait KUALITAS TATA KELOLA MENCEGAH DAN MEMBERANTAS KORUPSI ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 10,'name' => 'Indikator Penilaian Anda di Kabupaten/Kota ini Terkait KAPASITAS MENCEGAH DAN MEMBERANTAS KORUPSI ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 11,'name' => 'Indikator Penilaian Secara Umum tentang Kecenderungan Perilaku Korupsi di Kabupaten/Kota ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 11,'name' => 'Indikator Penilaian Anda terhadap Perilaku Korup/Suap para Pejabat Kabupaten/Kota ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 12,'name' => 'Indikator Kesan terhadap Pengetahuan Aparat tentang Strategi pencegahan dan pemberantasan korupsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 12,'name' => 'Indikator Penilaian terhadap Sistem Peradilan di Kabupaten/Kota ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 13,'name' => 'Indikator Kemampuan Pengedalian Intra Pribadi untuk Tidak Korupsi & Tidak Menerima Suap ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 13,'name' => 'Indikator Kemampuan Pengedalian Antar Pribadi untuk Tidak Korupsi & Tidak Menerima Suap ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 14,'name' => 'Indikator Adanya Standard yang Mengatur tentang PROSEDUR KERJA di Tingkat Provinsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 14,'name' => 'Indikator Adanya Standard yang Mengatur tentang PROSEDUR WAKTU di Tingkat Provinsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 14,'name' => 'Indikator Adanya Standard yang Mengatur tentang PROSEDUR BIAYA di Tingkat Provinsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 15,'name' => 'Indikator Terwujudnya dengan Baik IMPLEMENTASI Standard PROSEDUR KERJA di Tingkat Provinsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 15,'name' => 'Indikator Terwujudnya dengan Baik IMPLEMENTASI Standard PROSEDUR WAKTU KERJA di Tingkat Provinsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 15,'name' => 'Indikator Terwujudnya dengan Baik IMPLEMENTASI Standard PROSEDUR BIAYA di Tingkat Provinsi ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 16,'name' => 'Indikator Adanya STANDARD dan PROSEDUR KERJA di Lingkungan Pemerintah Pusat ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 16,'name' => 'Indikator Adanya STANDARD DALAM MENGATUR PROSEDUR WAKTU di  Lingkungan Pemerintah Pusat ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 16,'name' => 'Indikator Adanya STANDARD YANG MENGATUR TENTANG PROSEDUR BIAYA di  Lingkungan Pemerintah Pusat ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_1','dimension_id' => 17,'name' => 'Indikator Terwujudnya dengan Baik IMPLEMENTASI PROSEDUR KERJA di Lingkungan Pemerintah Pusat ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_2','dimension_id' => 17,'name' => 'Indikator Terwujudnya dengan Baik IMPLEMENTASI PROSEDUR WAKTU YANG TEPAT di Lingkungan Pemerintah Pusat ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
        DB::table('indicators')->insert(['indicator_number' => 'IND_3','dimension_id' => 17,'name' => 'Indikator Terwujudnya dengan Baik IMPLEMENTASI PROSEDUR BIAYA di Lingkungan Pemerintah Pusat ','created_at' => Carbon::now()->toDateTimeString(),'updated_at' => Carbon::now()->toDateTimeString()]);
    }
}
